<a href="https://colab.research.google.com/github/T3p/dqn-tutorial/blob/main/notebooks/3_deep_q_network_dqn_update.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#DQN Tutorial: Deep Q-Network (DQN)

## Part II: DQN Update and Training Loop

Based on the RLSS 2023 tutorial by Antonin Raffin https://github.com/araffin/rlss23-dqn-tutorial

<div>
    <img src="https://araffin.github.io/slides/dqn-tutorial/images/dqn/dqn.png" width="800"/>
</div>

### Introduction

In this notebook, you will finish the implementation of the [Deep Q-Network (DQN)](https://stable-baselines3.readthedocs.io/en/master/modules/dqn.html) algorithm (started in part I) by implementing the training loop and the DQN gradient update.

In [1]:
# for autoformatting
# !pip install jupyter-black
# %load_ext jupyter_black

### Install Dependencies

In [2]:
!pip install git+https://github.com/araffin/rlss23-dqn-tutorial/ --upgrade

  Cloning https://github.com/araffin/rlss23-dqn-tutorial/ to /tmp/pip-req-build-jzouzrvi
  Running command git clone --filter=blob:none --quiet https://github.com/araffin/rlss23-dqn-tutorial/ /tmp/pip-req-build-jzouzrvi
  Resolved https://github.com/araffin/rlss23-dqn-tutorial/ to commit ee0e4ff5dfe1c6502ebe4be744a40101e07f3f3b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 958.1/958.1 kB 24.9 MB/s eta 0:00:00
  Created wheel for dqn_tutorial: filename=dqn_tutorial-0.1.dev60+gee0e4ff5d-py3-none-any.whl size=19919 sha256=bc15139b38685a97e0088b97c541b09507e2e10a73e4ee157288ce4bfb74a89f
  Stored in directory: /tmp/pip-ephem-wheel-cache-8kplabdr/wheels/af/2e/9c/0f1eb59648e2b461f63a0651fabe409295f36419acefd51238
Successfully built dqn_tutorial
  Attempting uninstall: gymnasium
    Found existing installation: gymnasium 1.2.3
    Uninstalling gymnasium-1.2.3:
  

In [3]:
!apt-get install ffmpeg  # For visualization

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.


### Imports (from Part I)

In [4]:
from typing import Optional

import numpy as np
import torch as th
import gymnasium as gym
from gymnasium import spaces

# We implemented those components in part I
from dqn_tutorial.dqn import ReplayBuffer, epsilon_greedy_action_selection, collect_one_step, linear_schedule, QNetwork
from dqn_tutorial.dqn.evaluation import evaluate_policy
from dqn_tutorial.notebook_utils import show_videos

In [5]:
from pathlib import Path

import dqn_tutorial

video_folder = Path(dqn_tutorial.__file__).parent.parent  / "logs/videos"

## DQN Update rule (no target network)
<div>
    <img src="https://araffin.github.io/slides/dqn-tutorial/images/dqn/annotated_dqn.png" width="1000"/>
</div>


## Pytorch crash course (part II)

In [7]:
import torch as th

th.cuda.is_available()  # Use GPU for this part if you can

True

In [8]:
x = th.ones(3, requires_grad=True)  # A tensor I can compute gradients of

print(x)

def f(x):  # A differentiable function
  return th.sum(x**2)

y = f(x)  # A result I can differentiate

print(y)

tensor([1., 1., 1.], requires_grad=True)
tensor(3., grad_fn=<SumBackward0>)


In [9]:
y.backward(retain_graph=True)  # Compute gradient of y with respect to all of its inputs
x.grad  # Retrieve the gradient of y w.r.t. x

tensor([2., 2., 2.])

What happens if you run the above cell multiple times?

In [10]:
x.grad = None  # Clear previously computed gradients (otherwise they cumulate)
y.backward(retain_graph=True)
print(x.grad)

tensor([2., 2., 2.])


Here is another way to compute gradients

In [11]:
z = th.ones(3, requires_grad=True)

def g(x):
  return th.sum(x**3)

w = g(z)

th.autograd.grad(w, z)

(tensor([3., 3., 3.]),)

And here is the functional (jax-style) way:

In [12]:
dg = th.func.grad(g)
dg(z)

tensor([3., 3., 3.], grad_fn=<MulBackward0>)

Always keep in mind that keeping track of differentiable functions for computing gradients is computationally expensive (https://docs.pytorch.org/tutorials/beginner/understanding_leaf_vs_nonleaf_tutorial.html)

In [13]:
with th.no_grad():  # If you don't care about gradients w.r.t. v, you can spare pytorch some time
  v = f(g(f(g(x))**3 / f(g(f(z)))))
v

tensor(1.)

A typical situation: compute the gradients of a model w.r.t its parameters for some input

In [14]:
import torch.nn as nn

input = th.randn(5)  # a random example

target = f(input)  # a target value our model is trying to predict (regression)

model = nn.Sequential(  # a small NN model
    nn.Linear(5, 2),
    nn.ReLU(),
    nn.Linear(2, 1)
)

loss = (model(input) - target)**2  # squared loss

print(loss)

tensor([853.5131], grad_fn=<PowBackward0>)


First let's have a look into the model

In [15]:
from torch.nn.utils import parameters_to_vector, vector_to_parameters

with th.no_grad():

  # Model parameters
  params = model.parameters()

  print()
  print([p for p in params])

  # Model parameters with their names
  named_params = model.named_parameters()

  print()
  print([p for p in named_params])


  # Model parameters as a single flat tensor
  flat_params = parameters_to_vector(model.parameters())

  print()
  print(flat_params)


[Parameter containing:
tensor([[ 0.0556,  0.1281,  0.0854, -0.3617, -0.3843],
        [ 0.3211, -0.2874, -0.2236,  0.3280,  0.1839]], requires_grad=True), Parameter containing:
tensor([0.1593, 0.4132], requires_grad=True), Parameter containing:
tensor([[-0.2428, -0.0976]], requires_grad=True), Parameter containing:
tensor([0.3613], requires_grad=True)]

[('0.weight', Parameter containing:
tensor([[ 0.0556,  0.1281,  0.0854, -0.3617, -0.3843],
        [ 0.3211, -0.2874, -0.2236,  0.3280,  0.1839]], requires_grad=True)), ('0.bias', Parameter containing:
tensor([0.1593, 0.4132], requires_grad=True)), ('2.weight', Parameter containing:
tensor([[-0.2428, -0.0976]], requires_grad=True)), ('2.bias', Parameter containing:
tensor([0.3613], requires_grad=True))]

tensor([ 0.0556,  0.1281,  0.0854, -0.3617, -0.3843,  0.3211, -0.2874, -0.2236,
         0.3280,  0.1839,  0.1593,  0.4132, -0.2428, -0.0976,  0.3613])


Let's manually perform one step of gradient descent

In [16]:
step_size = 1e-3 # Step size for gradient descent

loss = (model(input) - target)**2

with th.no_grad():
  print("Before:", parameters_to_vector(model.parameters()))

  model.zero_grad()  # Clears the gradients of all the parameters of the model

  loss.backward(retain_graph=True)

  theta = parameters_to_vector(model.parameters())

  grad_theta = parameters_to_vector(p.grad for p in model.parameters())

  theta_new = theta - step_size * grad_theta  # Gradient descent (1 step)

  vector_to_parameters(theta_new, model.parameters())  # Assign the new parameters to the model

  print("After:", parameters_to_vector(model.parameters()))

Before: tensor([ 0.0556,  0.1281,  0.0854, -0.3617, -0.3843,  0.3211, -0.2874, -0.2236,
         0.3280,  0.1839,  0.1593,  0.4132, -0.2428, -0.0976,  0.3613])
After: tensor([ 0.0556,  0.1281,  0.0854, -0.3617, -0.3843,  0.3196, -0.2997, -0.2176,
         0.3005,  0.1875,  0.1593,  0.4075, -0.2428, -0.0057,  0.4197])


Pytorch optimizers allow to automatize the above procedure

In [17]:
loss = (model(input) - target)**2

with th.no_grad():
  print("Before:", parameters_to_vector(model.parameters()))

  optimizer = th.optim.SGD(model.parameters(), lr=step_size)

  optimizer.zero_grad()

  loss.backward(retain_graph=True)

  optimizer.step()

  print(th.nn.utils.clip_grad_norm_(
    model.parameters(),
    max_norm=float("inf")
  ))

  print("After:", parameters_to_vector(model.parameters()))

Before: tensor([ 0.0556,  0.1281,  0.0854, -0.3617, -0.3843,  0.3196, -0.2997, -0.2176,
         0.3005,  0.1875,  0.1593,  0.4075, -0.2428, -0.0057,  0.4197])
tensor(99.8576)
After: tensor([ 0.0556,  0.1281,  0.0854, -0.3617, -0.3843,  0.3195, -0.3004, -0.2172,
         0.2990,  0.1877,  0.1593,  0.4072, -0.2428,  0.0756,  0.4778])


### Exercise (15 minutes): write DQN update

**HINT**: DQN update is heavily inspired by FQI update: if you get stuck, you can take a look at what you did in the first notebook on FQI

**HINT**: The data sampled from the replay buffer uses the following structure:

```python
@dataclass
class ReplayBufferSamples:
    """
    A dataclass containing transitions from the replay buffer.
    """

    observations: np.ndarray  # same as states in the theory
    next_observations: np.ndarray
    actions: np.ndarray
    rewards: np.ndarray
    terminateds: np.ndarray
```

**HINT**: You can take a look at the section about Q-Network in the second notebook (DQN part I) to recall how to predict q-values using a q-network.

In [18]:
from dqn_tutorial.dqn.dqn_no_target import dqn_update_no_target as cheat_dqn_update_no_target

def dqn_update_no_target(
    q_net: QNetwork,
    optimizer: th.optim.Optimizer,
    replay_buffer: ReplayBuffer,
    batch_size: int,
    gamma: float,
) -> None:
    """
    Perform one gradient step on the Q-network
    using the data from the replay buffer.
    Note: this is the same as dqn_update in dqn.py, but without the target network.

    :param q_net: The Q-network to update
    :param optimizer: The optimizer to use
    :param replay_buffer: The replay buffer containing the transitions
    :param batch_size: The minibatch size, how many transitions to sample
    :param gamma: The discount factor
    """
    ### YOUR CODE HERE

    # Sample the replay buffer and convert them to PyTorch tensors
    # using `.to_torch()` method
    replay_data = replay_buffer.sample(batch_size).to_torch()

    # We should not compute gradient with respect to the target
    with th.no_grad():
        # Compute the Q-values for the next observations
        # (replay_data.next_observations)
        # (batch_size, n_actions)

        # Follow greedy policy: use the one with the highest value
        # shape: (batch_size,)
        # Note: tensor.max(dim=..) returns a tuple (max, indices) in PyTorch

        # If the episode is terminated, set the target to the reward
        # (same as FQI, you can use `th.logical_not` to mask the next q values)

        # 1-step TD target (TD(0) same as for FQI)
        td_target = ...

    # Get current Q-values estimates for the replay_data (batch_size, n_actions)

    # Select the Q-values corresponding to the actions that were selected
    # during data collection,
    # you should use `th.gather()`

    # Reshape from (batch_size, 1) to (batch_size,) to avoid broadcast error
    # You can use `tensor.squeeze(dim=..)`
    current_q_values = ...

    # Check for any shape/broadcast error
    # Current q-values must have the same shape as the TD target
    assert current_q_values.shape == (batch_size,), f"{current_q_values.shape} != {(batch_size,)}"
    assert current_q_values.shape == td_target.shape, f"{current_q_values.shape} != {td_target.shape}"

    # Compute the Mean Squared Error (MSE) loss
    # Optionally, one can use a Huber loss instead of the MSE loss
    loss = ...

    ### END OF YOUR CODE

    # Reset gradients
    optimizer.zero_grad()
    # Compute the gradients
    loss.backward()
    # Update the parameters of the q-network
    optimizer.step()

Let's test the implementation:

In [19]:
env = gym.make("CartPole-v1")
q_net = QNetwork(env.observation_space, env.action_space)
optimizer = th.optim.Adam(q_net.parameters(), lr=0.001)
replay_buffer = ReplayBuffer(2000, env.observation_space, env.action_space)

obs, _ = env.reset()
# Let's collect some data following an epsilon-greedy policy
for _ in range(1000):
    obs = collect_one_step(env, q_net, replay_buffer, obs, exploration_rate=0.1)

# Try to do some gradient steps:
for _ in range(10):
    dqn_update_no_target(q_net, optimizer, replay_buffer, batch_size=32, gamma=0.99)

AttributeError: 'ellipsis' object has no attribute 'shape'

### Exercise (10 minutes): write the training loop

Let's put everything together and implement the training loop that alternates between data collection and updating the Q-Network.
At first we will not use any target network.

<div>
    <img src="https://araffin.github.io/slides/dqn-tutorial/images/dqn/dqn_loop.png" width="600"/>
</div>

In [20]:
from dqn_tutorial.dqn.dqn_no_target import run_dqn_no_target as cheat_run_dqn_no_target

def run_dqn_no_target(
    env_id: str = "CartPole-v1",
    replay_buffer_size: int = 50_000,
    # Exploration schedule
    # (for the epsilon-greedy data collection)
    exploration_initial_eps: float = 1.0,
    exploration_final_eps: float = 0.01,
    n_timesteps: int = 20_000,
    update_interval: int = 2,
    learning_rate: float = 3e-4,
    batch_size: int = 64,
    gamma: float = 0.99,
    n_eval_episodes: int = 10,
    evaluation_interval: int = 1000,
    eval_exploration_rate: float = 0.0,
    seed: int = 2023,
    # device: Union[th.device, str] = "cpu",
    eval_render_mode: Optional[str] = None,  # "human", "rgb_array", None
) -> QNetwork:
    """
    Run Deep Q-Learning (DQN) on a given environment.
    (without target network)

    :param env_id: Name of the environment
    :param replay_buffer_size: Max capacity of the replay buffer
    :param exploration_initial_eps: The initial exploration rate
    :param exploration_final_eps: The final exploration rate
    :param n_timesteps: Number of timesteps in total
    :param update_interval: How often to update the Q-network
        (every update_interval steps)
    :param learning_rate: The learning rate to use for the optimizer
    :param batch_size: The minibatch size
    :param gamma: The discount factor
    :param n_eval_episodes: The number of episodes to evaluate the policy on
    :param evaluation_interval: How often to evaluate the policy
    :param eval_exploration_rate: The exploration rate to use during evaluation
    :param seed: Random seed for the pseudo random generator
    :param eval_render_mode: The render mode to use for evaluation
    """
    # Set seed for reproducibility
    # Seed Numpy as PyTorch pseudo random generators
    # Seed Numpy RNG
    np.random.seed(seed)
    # seed the RNG for all devices (both CPU and CUDA)
    th.manual_seed(seed)

    # Create the environment
    env = gym.make(env_id)
    assert isinstance(env.observation_space, spaces.Box)
    assert isinstance(env.action_space, spaces.Discrete)
    env.action_space.seed(seed)

    # Create the evaluation environment
    eval_env = gym.make(env_id, render_mode=eval_render_mode)
    eval_env.reset(seed=seed)
    eval_env.action_space.seed(seed)

    ### YOUR CODE HERE
    # TODO:
    # 1. Instantiate the Q-Network and the optimizer
    # 2. Instantiate the replay buffer
    # 3. Compute the current exploration rate (epsilon)
    # 4. Collect new transition by stepping in the env following
    # an epsilon-greedy strategy
    # 5. Update the Q-Network using gradient descent

    # Create the q-network

    # Create the optimizer (PyTorch `th.optim.Adam` will be helpful here)

    # Create the Replay buffer

    # Reset the env

    for current_step in range(1, n_timesteps + 1):
        # Compute the current exploration rate
        # according to the exploration schedule (update the value of epsilon)
        # you should use `linear_schedule()`

        # Do one step in the environment following an epsilon-greedy policy
        # and store the transition in the replay buffer
        # you can re-use `collect_one_step()`


        # Update the Q-Network every `update_interval` steps
        if (current_step % update_interval) == 0:
            # Do one gradient step (using `dqn_update_no_target()`)
            ...

        ### END OF YOUR CODE

        if (current_step % evaluation_interval) == 0:
            print()
            print(f"Evaluation at step {current_step}:")
            # Evaluate the current greedy policy (deterministic policy)
            evaluate_policy(eval_env, q_net, n_eval_episodes, eval_exploration_rate=eval_exploration_rate)
    return q_net

## Train a DQN agent on CartPole environment

In [21]:
import os
# create log folder
os.makedirs("../logs/", exist_ok=True)

In [22]:
env_id = "CartPole-v1"
q_net = run_dqn_no_target(env_id)


Evaluation at step 1000:
Mean episode reward: 9.20 +/- 0.75

Evaluation at step 2000:
Mean episode reward: 9.50 +/- 0.67

Evaluation at step 3000:
Mean episode reward: 9.60 +/- 0.49

Evaluation at step 4000:
Mean episode reward: 9.50 +/- 0.50

Evaluation at step 5000:
Mean episode reward: 9.20 +/- 0.98

Evaluation at step 6000:
Mean episode reward: 9.90 +/- 0.54

Evaluation at step 7000:
Mean episode reward: 9.60 +/- 1.02

Evaluation at step 8000:
Mean episode reward: 9.50 +/- 0.50

Evaluation at step 9000:
Mean episode reward: 9.40 +/- 0.49

Evaluation at step 10000:
Mean episode reward: 9.70 +/- 0.78

Evaluation at step 11000:
Mean episode reward: 9.00 +/- 1.10

Evaluation at step 12000:
Mean episode reward: 9.20 +/- 0.98

Evaluation at step 13000:
Mean episode reward: 9.40 +/- 1.02

Evaluation at step 14000:
Mean episode reward: 9.60 +/- 0.80

Evaluation at step 15000:
Mean episode reward: 9.20 +/- 0.98

Evaluation at step 16000:
Mean episode reward: 9.30 +/- 0.46

Evaluation at st

### Record and show video of the trained agent

In [23]:
eval_env = gym.make(env_id, render_mode="rgb_array")
n_eval_episodes = 3
eval_exploration_rate = 0.0
video_name = f"DQN_no_target_{env_id}"

evaluate_policy(
    eval_env,
    q_net,
    n_eval_episodes,
    eval_exploration_rate=eval_exploration_rate,
    video_name=video_name,
)

show_videos(video_folder, prefix=video_name)

Saving video to /usr/local/lib/python3.12/dist-packages/logs/videos/DQN_no_target_CartPole-v1.mp4


/usr/local/lib/python3.12/dist-packages/moviepy/config_defaults.py:47: SyntaxWarning: invalid escape sequence '\P'
  IMAGEMAGICK_BINARY = r"C:\Program Files\ImageMagick-6.8.8-Q16\magick.exe"


Mean episode reward: 10.00 +/- 0.82


## [Bonus] DQN Target Network


<div>
    <img src="https://araffin.github.io/slides/dqn-tutorial/images/dqn/target_q_network.png" width="1000"/>
</div>

The only things that is changing is when predicting the next q value.

In DQN without target, the online network with weights **$\theta$** is used:

$y = r_t + \gamma \cdot \max_{a \in A}(\hat{Q}_{\pi}(s_{t+1}, a; \theta))$


whereas with DQN with target network, the target q-network (a delayed copy of the q-network) with weights **$\theta^\prime$** is used instead:

$y = r_t + \gamma \cdot \max_{a \in A}(\hat{Q}_{\pi}(s_{t+1}, a; \theta^\prime))$


### Exercise (5 minutes): write the DQN update with target network

**HINT**: it is exactly the same as `dqn_update_no_target` expect for computing the next q-values

In [25]:
from dqn_tutorial.dqn.dqn import dqn_update as cheat_dqn_update

def dqn_update(
    q_net: QNetwork,
    q_target_net: QNetwork,
    optimizer: th.optim.Optimizer,
    replay_buffer: ReplayBuffer,
    batch_size: int,
    gamma: float,
) -> None:
    """
    Perform one gradient step on the Q-network
    using the data from the replay buffer.

    :param q_net: The Q-network to update
    :param q_target_net: The target Q-network, to compute the td-target.
    :param optimizer: The optimizer to use
    :param replay_buffer: The replay buffer containing the transitions
    :param batch_size: The minibatch size, how many transitions to sample
    :param gamma: The discount factor
    """

    # Sample the replay buffer and convert them to PyTorch tensors
    replay_data = replay_buffer.sample(batch_size).to_torch()

    with th.no_grad():
        ### YOUR CODE HERE
        # TODO: use the target q-network instead of the online q-network
        # to compute the next values

        # Compute the Q-values for the next observations (batch_size, n_actions)
        # using the target network

        ...

        # Follow greedy policy: use the one with the highest value
        # (batch_size,)

        # If the episode is terminated, set the target to the reward

        # 1-step TD target

        ### END OF YOUR CODE

    # Get current Q-values estimates for the replay_data (batch_size, n_actions)
    q_values = q_net(replay_data.observations)
    # Select the Q-values corresponding to the actions that were selected
    # during data collection
    current_q_values = th.gather(q_values, dim=1, index=replay_data.actions)
    # Reshape from (batch_size, 1) to (batch_size,) to avoid broadcast error
    current_q_values = current_q_values.squeeze(dim=1)

    # Check for any shape/broadcast error
    # Current q-values must have the same shape as the TD target
    assert current_q_values.shape == (batch_size,), f"{current_q_values.shape} != {(batch_size,)}"
    assert current_q_values.shape == td_target.shape, f"{current_q_values.shape} != {td_target.shape}"

    # Compute the Mean Squared Error (MSE) loss
    # Optionally, one can use a Huber loss instead of the MSE loss
    loss = ((current_q_values - td_target) ** 2).mean()
    # Huber loss
    # loss = th.nn.functional.smooth_l1_loss(current_q_values, td_target)

    # Reset gradients
    optimizer.zero_grad()
    # Compute the gradients
    loss.backward()
    # Update the parameters of the q-network
    optimizer.step()

### Updated training loop

In [26]:
def run_dqn(
    env_id: str = "CartPole-v1",
    replay_buffer_size: int = 50_000,
    # How often do we copy the parameters from the Q-network to the target network
    target_network_update_interval: int = 1000,
    # Warmup phase
    learning_starts: int = 100,
    # Exploration schedule
    # (for the epsilon-greedy data collection)
    exploration_initial_eps: float = 1.0,
    exploration_final_eps: float = 0.01,
    exploration_fraction: float = 0.1,
    n_timesteps: int = 20_000,
    update_interval: int = 2,
    learning_rate: float = 3e-4,
    batch_size: int = 64,
    gamma: float = 0.99,
    n_hidden_units: int = 64,
    n_eval_episodes: int = 10,
    evaluation_interval: int = 1000,
    eval_exploration_rate: float = 0.0,
    seed: int = 2023,
    # device: Union[th.device, str] = "cpu",
    eval_render_mode: Optional[str] = None,  # "human", "rgb_array", None
) -> QNetwork:
    """
    Run Deep Q-Learning (DQN) on a given environment.
    (with a target network)

    :param env_id: Name of the environment
    :param replay_buffer_size: Max capacity of the replay buffer
    :param target_network_update_interval: How often do we copy the parameters
         to the target network
    :param learning_starts: Warmup phase to fill the replay buffer
        before starting the optimization.
    :param exploration_initial_eps: The initial exploration rate
    :param exploration_final_eps: The final exploration rate
    :param exploration_fraction: The fraction of the number of steps
        during which the exploration rate is annealed from
        initial_eps to final_eps.
        After this many steps, the exploration rate remains constant.
    :param n_timesteps: Number of timesteps in total
    :param update_interval: How often to update the Q-network
        (every update_interval steps)
    :param learning_rate: The learning rate to use for the optimizer
    :param batch_size: The minibatch size
    :param gamma: The discount factor
    :param n_hidden_units: Number of units for each hidden layer
        of the Q-Network.
    :param n_eval_episodes: The number of episodes to evaluate the policy on
    :param evaluation_interval: How often to evaluate the policy
    :param eval_exploration_rate: The exploration rate to use during evaluation
    :param seed: Random seed for the pseudo random generator
    :param eval_render_mode: The render mode to use for evaluation
    """
    # Set seed for reproducibility
    # Seed Numpy as PyTorch pseudo random generators
    # Seed Numpy RNG
    np.random.seed(seed)
    # seed the RNG for all devices (both CPU and CUDA)
    th.manual_seed(seed)

    # Create the environment
    env = gym.make(env_id)
    # For highway env
    env = gym.wrappers.FlattenObservation(env)
    env = gym.wrappers.RecordEpisodeStatistics(env)
    assert isinstance(env.observation_space, spaces.Box)
    assert isinstance(env.action_space, spaces.Discrete)
    env.action_space.seed(seed)

    # Create the evaluation environment
    eval_env = gym.make(env_id, render_mode=eval_render_mode)
    eval_env = gym.wrappers.FlattenObservation(eval_env)
    eval_env.reset(seed=seed)
    eval_env.action_space.seed(seed)

    # Create the q-network
    q_net = QNetwork(env.observation_space, env.action_space, n_hidden_units=n_hidden_units)
    # Create the target network
    q_target_net = QNetwork(env.observation_space, env.action_space, n_hidden_units=n_hidden_units)
    # Copy the parameters of the q-network to the target network
    q_target_net.load_state_dict(q_net.state_dict())

    # For flappy bird
    if env.observation_space.dtype == np.float64:
        q_net.double()
        q_target_net.double()

    # Create the optimizer, we only optimize the parameters of the q-network
    optimizer = th.optim.Adam(q_net.parameters(), lr=learning_rate)

    # Create the Replay buffer
    replay_buffer = ReplayBuffer(replay_buffer_size, env.observation_space, env.action_space)
    # Reset the env
    obs, _ = env.reset(seed=seed)
    for current_step in range(1, n_timesteps + 1):
        # Update the current exploration schedule (update the value of epsilon)
        exploration_rate = linear_schedule(
            exploration_initial_eps,
            exploration_final_eps,
            current_step,
            int(exploration_fraction * n_timesteps),
        )
        # Do one step in the environment following an epsilon-greedy policy
        # and store the transition in the replay buffer
        obs = collect_one_step(
            env,
            q_net,
            replay_buffer,
            obs,
            exploration_rate=exploration_rate,
            verbose=0,
        )

        # Update the target network
        # by copying the parameters from the Q-network every target_network_update_interval steps
        if (current_step % target_network_update_interval) == 0:
            q_target_net.load_state_dict(q_net.state_dict())

        # Update the Q-network every update_interval steps
        # after learning_starts steps have passed (warmup phase)
        if (current_step % update_interval) == 0 and current_step > learning_starts:
            # Do one gradient step
            dqn_update(q_net, q_target_net, optimizer, replay_buffer, batch_size, gamma=gamma)

        if (current_step % evaluation_interval) == 0:
            print()
            print(f"Evaluation at step {current_step}:")
            print(f"exploration_rate={exploration_rate:.2f}")
            # Evaluate the current greedy policy (deterministic policy)
            evaluate_policy(eval_env, q_net, n_eval_episodes, eval_exploration_rate=eval_exploration_rate)
            # Save a checkpoint
            th.save(q_net.state_dict(), f"../logs/q_net_checkpoint_{env_id}_{current_step}.pth")
    return q_net

## Train DQN agent with target network on CartPole env

In [27]:
# Tuned hyperparameters from the RL Zoo3 of the Stable Baselines3 library
# https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/dqn.yml

env_id = "CartPole-v1"

q_net = run_dqn(
    env_id=env_id,
    replay_buffer_size=100_000,
    # Note: you can remove the target network
    # by setting target_network_update_interval=1
    target_network_update_interval=10,
    learning_starts=1000,
    exploration_initial_eps=1.0,
    exploration_final_eps=0.04,
    exploration_fraction=0.1,
    n_timesteps=80_000,
    update_interval=2,
    learning_rate=1e-3,
    batch_size=64,
    gamma=0.99,
    n_eval_episodes=10,
    evaluation_interval=5000,
    # No exploration during evaluation
    # (deteministic policy)
    eval_exploration_rate=0.0,
    seed=2022,
)


Evaluation at step 5000:
exploration_rate=0.40
Mean episode reward: 248.30 +/- 108.67

Evaluation at step 10000:
exploration_rate=0.04
Mean episode reward: 266.20 +/- 53.94

Evaluation at step 15000:
exploration_rate=0.04
Mean episode reward: 165.20 +/- 28.99

Evaluation at step 20000:
exploration_rate=0.04
Mean episode reward: 221.50 +/- 28.89

Evaluation at step 25000:
exploration_rate=0.04
Mean episode reward: 276.70 +/- 58.35

Evaluation at step 30000:
exploration_rate=0.04
Mean episode reward: 268.70 +/- 30.26

Evaluation at step 35000:
exploration_rate=0.04
Mean episode reward: 9.90 +/- 0.70

Evaluation at step 40000:
exploration_rate=0.04
Mean episode reward: 500.00 +/- 0.00

Evaluation at step 45000:
exploration_rate=0.04
Mean episode reward: 500.00 +/- 0.00

Evaluation at step 50000:
exploration_rate=0.04
Mean episode reward: 500.00 +/- 0.00

Evaluation at step 55000:
exploration_rate=0.04
Mean episode reward: 500.00 +/- 0.00

Evaluation at step 60000:
exploration_rate=0.04
M

### Visualize the trained agent

In [28]:
eval_env = gym.make(env_id, render_mode="rgb_array")
n_eval_episodes = 3
eval_exploration_rate = 0.0
video_name = f"DQN_{env_id}"

# Optional: load checkpoint
# q_net = QNetwork(eval_env.observation_space, eval_env.action_space, n_hidden_units=64)
# q_net.load_state_dict(th.load("../logs/q_net_checkpoint_CartPole-v1_75000.pth"))

evaluate_policy(
    eval_env,
    q_net,
    n_eval_episodes,
    eval_exploration_rate=eval_exploration_rate,
    video_name=video_name,
)

show_videos(video_folder, prefix=video_name)

Saving video to /usr/local/lib/python3.12/dist-packages/logs/videos/DQN_CartPole-v1.mp4
Mean episode reward: 500.00 +/- 0.00


## Training DQN agent on flappy bird:

This is a gymnasium environment by Antonin Raffin.

You can go in the [GitHub repo](https://github.com/araffin/flappy-bird-gymnasium/tree/patch-1) to learn more about this environment.

<div>
    <img src="https://raw.githubusercontent.com/markub3327/flappy-bird-gymnasium/main/imgs/dqn.gif" width="300"/>
</div>


In [29]:
!pip install "flappy-bird-gymnasium @ git+https://github.com/araffin/flappy-bird-gymnasium@patch-1"

  Cloning https://github.com/araffin/flappy-bird-gymnasium (to revision patch-1) to /tmp/pip-install-hghxj8p0/flappy-bird-gymnasium_6a551357bf9247018f6580cc1a93a7da
  Running command git clone --filter=blob:none --quiet https://github.com/araffin/flappy-bird-gymnasium /tmp/pip-install-hghxj8p0/flappy-bird-gymnasium_6a551357bf9247018f6580cc1a93a7da
  Running command git checkout -b patch-1 --track origin/patch-1
  Switched to a new branch 'patch-1'
  Branch 'patch-1' set up to track remote branch 'patch-1' from 'origin'.
  Resolved https://github.com/araffin/flappy-bird-gymnasium to commit 8828737242a38c0cd18c4260819fe7e695fb6bae
  Preparing metadata (setup.py) ... done
  Created wheel for flappy-bird-gymnasium: filename=flappy_bird_gymnasium-0.2.2-py3-none-any.whl size=1074471 sha256=3c19e258a4f1c3792d22bb8eea064fd25ea300a51278c70b0b92938b69969000
  Stored in directory: /tmp/pip-ephem-wheel-cache-jcq6pt10/wheels/b0/48/e5/e447569a935d86b16cf1fd7560c83ae96ea0ebaaec403a04f2
Successfully b

In [30]:
import flappy_bird_gymnasium  # noqa: F401

In [ ]:
env_id = "FlappyBird-v0"

q_net = run_dqn(
    env_id=env_id,
    replay_buffer_size=100_000,
    # Note: you can remove the target network
    # by setting target_network_update_interval=1
    target_network_update_interval=250,
    learning_starts=10_000,
    exploration_initial_eps=1.0,
    exploration_final_eps=0.03,
    exploration_fraction=0.1,
    n_timesteps=500_000,
    update_interval=4,
    learning_rate=1e-3,
    batch_size=128,
    gamma=0.98,
    n_eval_episodes=5,
    evaluation_interval=50000,
    n_hidden_units=256,
    # No exploration during evaluation
    # (deteministic policy)
    eval_exploration_rate=0.0,
    seed=2023,
    eval_render_mode=None,
)

### Record a video of the trained agent

In [ ]:
eval_env = gym.make(env_id, render_mode="rgb_array")
n_eval_episodes = 3
eval_exploration_rate = 0.00
video_name = f"DQN_{env_id}"


# Optional: load checkpoint
q_net = QNetwork(eval_env.observation_space, eval_env.action_space, n_hidden_units=256)
# Convert weights from float32 to float64 to match flappy bird obs
q_net.double()
q_net.load_state_dict(th.load("../logs/q_net_checkpoint_FlappyBird-v0_200000.pth"))

evaluate_policy(
    eval_env,
    q_net,
    n_eval_episodes,
    eval_exploration_rate=eval_exploration_rate,
    video_name=video_name,
)

show_videos(video_folder, prefix=video_name)

### Going further

- analyse the learned q-values
- explore different value for the target update, use soft update instead of hard-copy
- experiment with Huber loss (smooth l1 loss) instead of l2 loss (mean squared error)
- play with different environments
- implement a CNN to play flappybird/pong from pixels (need to stack frames)
- implement DQN extensions (double Q-learning, prioritized experience replay, ...)

## Conclusion

In this notebook, you have seen how to implement the DQN algorithm (update rule and training loop) using all the components from part I (replay buffer, epsilon-greedy exploration strategy, Q-Network, ...).